# -*- coding: utf-8 -*-
"""Cat boost model DEPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11-WVdqXoHn5kobey2K19K5zygjt0Hf8c
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

acc_data = pd.read_csv("/content/Ultimate_Final.csv")

acc_data['Risk_Score'] = acc_data['Accident_Count'] * acc_data['Severity']
acc_data['Risk_Score'] = np.log1p(acc_data['Risk_Score'])
risk_threshold = acc_data['Risk_Score'].median()
acc_data['High_Risk'] = (acc_data['Risk_Score'] > risk_threshold).astype(int)

df_filled = acc_data.copy()
numeric_cols = df_filled.select_dtypes(include=[np.number]).columns
df_filled[numeric_cols] = df_filled[numeric_cols].fillna(df_filled[numeric_cols].mean())

num_cols = [
    'Year', 'Month', 'Latitude', 'Longitude',
    'Temperature(F)', 'Humidity(%)', 'Pressure(in)', 'Visibility(mi)',
    'Wind_Speed(mph)', 'Precipitation(in)', 'Traffic_Event_Count',
    'Traffic_Severity', 'DelayFromTypicalTraffic(mins)',
    'DelayFromFreeFlowSpeed(mins)', 'Traffic_Distance'
]

cat_cols = ['State','County','City']

X = df_filled[num_cols + cat_cols]
y = df_filled['High_Risk']

plt.figure(figsize=(10,8))
sns.scatterplot(
    x='Longitude', y='Latitude',
    hue='High_Risk',
    data=df_filled,
    palette={0: 'blue', 1: 'red'},
    alpha=0.5
)
plt.title('Accidents by Location (Red = High Risk)')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='High_Risk', data=df_filled, palette='Set2')
plt.title('High-Risk vs Low-Risk Accident Areas')
plt.xlabel('High_Risk')
plt.ylabel('Number of Samples')
plt.show()

plt.figure(figsize=(10,6))
sns.histplot(acc_data['Risk_Score'], bins=50, kde=True, color='red')
plt.title('Risk Score Distribution')
plt.xlabel('Risk Score')
plt.ylabel('Frequency')
plt.show()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

cat_indices = [X.columns.get_loc(col) for col in cat_cols]

model_cb = CatBoostClassifier(
    iterations=1200,
    depth=10,
    learning_rate=0.05,
    loss_function='Logloss',
    eval_metric='Accuracy',
    random_seed=42,
    verbose=200,
    task_type="GPU"
)

model_cb.fit(
    X_train,
    y_train,
    cat_features=cat_indices,
    eval_set=(X_test, y_test),
    verbose=200
)

y_pred = model_cb.predict(X_test)

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

feature_importances = model_cb.get_feature_importance(prettified=True)
print("\nFeature Importances:")
print(feature_importances)